"""add_bible_snapshot_tracking

Revision ID: e5aa736879cf
Revises: 6d2e6c5da1d8
Create Date: 2026-01-07 01:40:02.830130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5aa736879cf'
down_revision: Union[str, Sequence[str], None] = '6d2e6c5da1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'name', name='uix_bible_snapshot_name')
    )
    op.create_index(op.f('ix_bible_snapshots_id'), 'bible_snapshots', ['id'], unique=False)
    op.add_column('history', sa.Column('bible_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'bible_snapshot')
    op.drop_index(op.f('ix_bible_snapshots_id'), table_name='bible_snapshots')
    op.drop_table('bible_snapshots')
    # ### end Alembic commands ###
